/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FastRadioGroup: typeof import('./src/components/fast-radio-group/src/fast-radio-group.vue')['default']
    FastSelect: typeof import('./src/components/fast-select/src/fast-select.vue')['default']
    FastTableColumn: typeof import('./src/components/fast-table-column/src/fast-table-column.vue')['default']
    FastUser: typeof import('./src/components/fast-user/src/fast-user.vue')['default']
    Lang: typeof import('./src/components/lang/index.vue')['default']
    MdEditor: typeof import('./src/components/md-editor/index.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/src/svg-icon.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    WangEditor: typeof import('./src/components/wang-editor/index.vue')['default']
  }
}
